### ISSUE TITLE
Don't load all tabs in workspace when switching to it

### ISSUE THREAD

**Issue by cronco** [fonse/tab-workspaces#10]
If you have a lot of tabs in a workspace this can be a real performance killer.

**Comment by fonse** [comment]
Sadly, there's [no way to open a tab and not load it](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create) with the WebExtension API.

**Comment by multimulti** [comment]
@fonse Ok, what about this workaround: 
Don't (re)create the real tabs but create placeholders (just locally stored dummy HTML pages with the titles of the real tabs). Then, when the user clicks any tab (or the first tab is automatically displayed), it will be active (which you can detect either with the api or even with javascript contained in the dummy HTML) and then you can use tabs.update to set this tab to the real url which will then load it.
This way only tabs actively addressed by the user will get loaded as suggested by (apparently) a multitude of users.

**Comment by multimulti** [comment]
@fonse Extra credit for caching the DOM elements of the real pages. Then, if a tab becomes active, don't update to the real url but show these DOM elements (so that the page looks the same as last visited). Display a message in the corner saying "This is the cached version of this page. Please click here to reload". More extra credit for storing these DOM elements encrypted as to not expose some secret user-data on disk. More extra credit for making it all user-configurable in your addon's settings (auto reload yes/no, etc.) 😃

**Comment by fonse** [comment]
That's actually very clever.

I don't know when I'll update this extension, but that's certainly something to keep in mind.

**Comment by multimulti** [comment]
I would imagine that, as FF57 is now being rolled out, some of the 86.251 users of Quicksaver's "Tab Groups" will now come to your addon, creating new motivation. Maybe you could even get a small Kickstarter or something similar going, where people can vote on functionality with their money!
